source 'https://rubygems.org'

gem 'rails', '3.2.3'
gem 'jquery-rails'
gem "twitter-bootstrap-rails"

gem 'grape', :git => 'https://github.com/intridea/grape', :branch => 'frontier'
gem 'redis'
gem 'hiredis'
gem 'rack-stream', :git => 'https://github.com/intridea/rack-stream'
gem 'thin'
gem 'faye'

group :development, :test do
  gem 'debugger'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end